wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.17.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718944322
    t:
      1:
      - 55
      3:
      - 23
      4: 3.7.16
      5: 0.17.1
      8:
      - 3
      - 8
      13: windows-amd64
